# Generated by Django 4.2.1 on 2023-05-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_alter_event_ticket_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='gigs_event_date_f25d1a_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('gig', 'gig'), ('club', 'club')], default='gig', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='gigs_event_date_8c0144_idx'),
        ),
    ]
