# Generated by Django 4.2.1 on 2023-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new_field',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
