# Generated by Django 4.2.1 on 2023-05-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_alter_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='new_field',
        ),
    ]
