# Generated by Django 4.2.1 on 2023-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_remove_event_sold_out_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('tickets on sale', 'tickets on sale'), ('announced', 'announced'), ('sold out', 'sold out'), ('cancelled', 'cancelled'), ('postponed', 'postponed')], default='tickets_available', max_length=50),
        ),
    ]
