# Generated by Django 4.2.1 on 2023-05-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0010_alter_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
