# Generated by Django 4.2.1 on 2023-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_alter_venue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
