# Generated by Django 4.2.1 on 2023-05-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_alter_venue_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(choices=[('Edinburgh', 'Edinburgh'), ('Glasgow', 'Glasgow')], default='Edinburgh', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('gig', 'gig'), ('club', 'club'), ('other', 'other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('tickets on sale', 'tickets on sale'), ('just announced', 'just announced'), ('sold out', 'sold out'), ('cancelled', 'cancelled'), ('postponed', 'postponed')], max_length=50),
        ),
    ]
