# Generated by Django 4.2.1 on 2023-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0014_venue_location_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(choices=[('Edinburgh', 'Edinburgh'), ('Glasgow', 'Glasgow'), ('other', 'other')], max_length=250),
        ),
    ]
