# Generated by Django 4.2.1 on 2023-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0018_alter_event_event_type_alter_event_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(choices=[('Edinburgh', 'Edinburgh'), ('Glasgow', 'Glasgow'), ('other', 'other'), ('unknown', 'unknown')], default='Edinburgh', max_length=250),
        ),
    ]
