# Generated by Django 4.2.1 on 2023-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0020_event_promoter_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='promoter',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
